// <auto-generated />
namespace ToxTracker.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _20210501Migration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20210501Migration));
        
        string IMigrationMetadata.Id
        {
            get { return "202105012155281_20210501Migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
